### ISSUE TITLE
Segfaulting on python3 - UnboundLocalError: local variable

### ISSUE THREAD

**Issue by Panzerfather** [twesterhever/squid-asnbl#2]
I was asked by Adolf Belka from the IPFire-Team to also raise a bug report for a segfaulting problem running the helper with squid and python3. I will link the original bug report from the IPFire Bugzilla page below, because it'll be easier for anyone to track the reason and also have the patch included to solve the problem. The patch is currently running stable for nearly 5 months without any problem on different machines affected by this problem.

Short summary for the root cause of this exception and how to solve it:

The python3 interpreter sometimes detects the local return variable if it was a misused global variable (false detection). To solve it, the local variable has be declared before it's first use and the use of the global ASNDB has to be slightly changed.

Exception:

```
Mar 01 01:27:14 squid-asnbl-helper[32004] WARN: Destination 'IP_ADDRESS_OF_PROXY' resolves to IP addresses 'IP_ADDRESS_OF_PROXY' without corresponding ASN, probably selectively announced
Mar 01 01:27:14 squid-asnbl-helper[32004] INFO: Denying access to destination 'IP_ADDRESS_OF_PROXY' due to suspected selective announcements
Traceback (most recent call last):
  File "/usr/bin/asnbl-helper.py", line 493, in <module>
    resolvedasn = resolve_asn(singleip, ASNDB)
  File "/usr/bin/asnbl-helper.py", line 193, in resolve_asn
    if not result.asn:
UnboundLocalError: local variable 'result' referenced before assignment
2023/03/01 01:34:23 kid1| WARNING: external_acl_type #Hlpr3 exited
...
Mar 01 01:34:24 squid-asnbl-helper[32478] WARN: No ASNBL configured. This is acceptable as long as this script is configured to do anything, you just have been warned...
Traceback (most recent call last):
  File "/usr/bin/asnbl-helper.py", line 493, in <module>
    resolvedasn = resolve_asn(singleip, ASNDB)
  File "/usr/bin/asnbl-helper.py", line 193, in resolve_asn
    if not result.asn:
UnboundLocalError: local variable 'result' referenced before assignment
...
2023/03/01 01:34:24 kid1| FATAL: The external_acl_type helpers are crashing too rapidly, need help!
```

Links:

Bug report: [https://bugzilla.ipfire.org/show_bug.cgi?id=13023](https://bugzilla.ipfire.org/show_bug.cgi?id=13023)
Comment 1: [https://bugzilla.ipfire.org/show_bug.cgi?id=13023#c11](https://bugzilla.ipfire.org/show_bug.cgi?id=13023#c11)
Comment 2: [https://bugzilla.ipfire.org/show_bug.cgi?id=13023#c19](https://bugzilla.ipfire.org/show_bug.cgi?id=13023#c19)
Comment 3: [https://bugzilla.ipfire.org/show_bug.cgi?id=13023#c23](https://bugzilla.ipfire.org/show_bug.cgi?id=13023#c23)

**Comment by twesterhever** [comment]
Thank you very much for raising this, I'll look into it.

**Comment by twesterhever** [comment]
https://github.com/twesterhever/squid-asnbl/commit/6465a1d7dae6e10a4e8ecbe40aa927782a812679 incorporates the upstream patch from IPFire.
